package com.example.ui.navigation

sealed class Screen(val route: String) {
    object Splash : Screen("splash")
    object Onboarding : Screen("onboarding")
    object Home : Screen("home")
    object Services : Screen("services")
    object ServiceDetail : Screen("service_detail")
    object ServiceRequestForm : Screen("service_request_form")
    object ServiceRequestDetail : Screen("service_request_detail")
    object Portfolio : Screen("portfolio")
    object PortfolioDetail : Screen("portfolio_detail")
    object Blogs : Screen("blogs")
    object BlogDetail : Screen("blog_detail")
    object AboutUs : Screen("about_us")
    object ContactUs : Screen("contact_us")
    object Login : Screen("login")
    object Register : Screen("register")
    data class EmailVerification(val email: String) : Screen("email_verification")
    object ForgotPassword : Screen("forgot_password")
    data class ResetPassword(val email: String) : Screen("reset_password")
    object UserDashboard : Screen("user_dashboard")
    object MyRequests : Screen("my_requests")
    object UserProfile : Screen("user_profile")
    object EditProfile : Screen("edit_profile")
    object Notifications : Screen("notifications")
    object Favorites : Screen("favorites")
    object SupportChat : Screen("support_chat")
    object SupportTickets : Screen("support_tickets")
    object CreateTicket : Screen("create_ticket")
    object Feedback : Screen("feedback")
    object Training : Screen("training")
    object AdminDashboard : Screen("admin_dashboard")
    object AdminServices : Screen("admin_services")
    object AdminRequests : Screen("admin_requests")
    object AdminUsers : Screen("admin_users")
    object AdminBlogs : Screen("admin_blogs")
    object AdminPortfolio : Screen("admin_portfolio")
    object AdminMessages : Screen("admin_messages")
    object AdminAuditLogs : Screen("admin_audit_logs")
    object AdminTickets : Screen("admin_tickets")
    object AdminFeedback : Screen("admin_feedback")
    object Settings : Screen("settings")
    object GlobalSearch : Screen("global_search")
}
